# Generated by Django 4.2.6 on 2023-11-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0012_table001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransactionmodel',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
