# Generated by Django 4.2.6 on 2023-11-14 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0013_alter_banktransactionmodel_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table001',
        ),
    ]
