# Generated by Django 4.2.6 on 2023-11-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0015_banktransactionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransactionhistory',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
