# Generated by Django 4.2.6 on 2023-11-15 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0017_banktransactionhistory_bank_trans'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransactionhistory',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.bankmodel'),
        ),
    ]
