# Generated by Django 4.2.6 on 2023-11-16 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0018_banktransactionhistory_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransactionhistory',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
