# Generated by Django 4.2.6 on 2023-11-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0019_alter_banktransactionhistory_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransactionmodel',
            name='by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='banktransactionmodel',
            name='last_action',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
